export enum KeyEnum {
  ADMIN = "admin",
  USER = "user",

  ASSIGN_ROLE_TO_USER = "assignRoleToUser",
  UN_ASSIGN_ROLE_TO_USER = "unAssignRoleToUser",
  ROLE_ACCESS_CREATE = "roleAccessCreate",
  ROLE_ACCESS_UPDATE = "roleAccessUpdate",
  ROLE_ACCESS_DELETE = "roleAccessDelete",
  ROLE_ACCESS_GET = "roleAccessGet",
  ROLE_ACCESS_GET_ALL = "roleAccessGetAll",

  PERMISSION_CREATE = "permissionCreate",
  PERMISSION_UPDATE = "permissionUpdate",
  PERMISSION_DELETE = "permissionDelete",
  PERMISSION_GET = "permissionGet",
  PERMISSION_GET_ALL = "permissionGetAll",

  GET_ACCESS_TOKEN = "getAccessToken",
  GET_REFRESH_TOKEN = "getRefreshToken",
  USER_REGISTRATION = "userRegistration",
  USER_LOGIN = "userLogin",
  ADMIN_LOGIN = "adminLogin",
  USER_LOGOUT = "userLogout",
  USER_REFRESH = "userRefresh",
  USER_UPDATE_PASSWORD = "userUpdatePassword",
  USER_UPDATE = "userUpdate",
  USER_DELETE = "userDelete",
  USER_DELETE_BY_UID = "userDeleteByUID",
  USER_GET = "userGet",
  USER_GET_ALL = "userGetAll",
  USER_GET_BY_UID = "userGetByUid",
  USER_GET_BY_REFER_CODE = "userGetByReferCode",
  USER_GET_BY_EMAIL = "userGetByEmail",
  USER_GET_BY_USERNAME = "userGetByUsername",
  USER_CHANGE_PROFILE = "userChangeProfile",

  ADDRESS_CREATE = "addressCreate",
  ADDRESS_UPDATE = "addressUpdate",
  ADDRESS_DELETE_BY_UID = "addressDeleteByUid",
  ADDRESS_DELETE = "addressDelete",
  ADDRESS_GET = "addressGet",
  ADDRESS_GET_ALL = "addressGetAll",
  ADDRESS_GET_BY_UID = "addressGetByUid",

  PHARMA_SCHEDULING_CREATE = "pharmaSchedulingCreate",
  PHARMA_SCHEDULING_UPDATE = "pharmaSchedulingUpdate",
  PHARMA_SCHEDULING_DELETE = "pharmaSchedulingDelete",
  PHARMA_SCHEDULING_GET = "pharmaSchedulingGet",
  PHARMA_SCHEDULING_GET_ALL = "pharmaSchedulingGetAll",

  MEDICAL_CONDITIONS_CREATE = "medicalConditionsCreate",
  MEDICAL_CONDITIONS_UPDATE = "medicalConditionsUpdate",
  MEDICAL_CONDITIONS__DELETE = "medicalConditionsDelete",
  MEDICAL_CONDITIONS_GET = "medicalConditionsGet",
  MEDICAL_CONDITIONS_GET_ALL = "medicalConditionsGetAll",

  MEDICAL_HISTORY_CREATE = "medicalHistoryCreate",
  MEDICAL_HISTORY_UPDATE = "medicalHistoryUpdate",
  MEDICAL_HISTORY_DELETE = "medicalHistoryDelete",
  MEDICAL_HISTORY_GET = "medicalHistoryGet",
  MEDICAL_HISTORY_GET_ALL = "medicalHistoryGetAll",

  TEST_REPORT_CREATE = "testReportCreate",
  TEST_REPORT_UPDATE = "testReportUpdate",
  TEST_REPORT_DELETE = "testReportDelete",
  TEST_REPORT_GET = "testReportGet",
  TEST_REPORT_GET_ALL = "testReportGetAll",

  WEIGHT_UPDATE_CREATE = "weightUpdateCreate",
  WEIGHT_UPDATE_UPDATE = "weightUpdateUpdate",
  WEIGHT_UPDATE_DELETE = "weightUpdateDelete",
  WEIGHT_UPDATE_GET = "weightUpdateGet",
  WEIGHT_UPDATE_GET_ALL = "weightUpdateGetAll",

  FILEUPLOAD = "fileupload",
  S3UPLOAD = "s3upload",
  S3_PUBLIC_URL_GET = "s3PublicUrlGet",

  WALLET_SETTING_CREATE = "walletSettingCreate",
  WALLET_SETTING_UPDATE = "walletSettingUpdate",
  WALLET_SETTING_DELETE = "walletSettingDelete",
  WALLET_SETTING_GET = "walletSettingGet",
  WALLET_SETTING_GET_ALL = "walletSettingGetAll",

  WALLET_SEND_MONEY = "walletSendMoney",
  WALLET_GET = "walletGet",
  WALLET_GET_ALL = "walletGetAll",
  WALLET_CREATE = "walletCreate",
  WALLET_UPDATE = "walletUpdate",
  WALLET_DELETE = "walletDelete",
  WALLET_DEDUCT = "walletDeduct",
  WALLET_POINT_TO_CASH = "walletPointToCash",

  PHARMA_SCHEDULE_SETTING_CREATE = "pharmaScheduleSettingCreate",
  PHARMA_SCHEDULE_SETTING_UPDATE = "pharmaScheduleSettingUpdate",
  PHARMA_SCHEDULE_SETTING_DELETE = "pharmaScheduleSettingDelete",
  PHARMA_SCHEDULE_SETTING_GET = "pharmaScheduleSettingGet",
  PHARMA_SCHEDULE_SETTING_GET_ALL = "pharmaScheduleSettingGetAll",

  HEALTH_INFORMATION_BLOG_HOME = "healthInformationBlogHome",
  HEALTH_INFORMATION_CREATE = "healthInformationCreate",
  HEALTH_INFORMATION_UPDATE = "healthInformationUpdate",
  HEALTH_INFORMATION_DELETE = "healthInformationDelete",
  HEALTH_INFORMATION_GET = "healthInformationGet",
  HEALTH_INFORMATION_GET_ALL = "healthInformationGetAll",

  HEALTH_INFORMATION_CATEGORY_CREATE = "healthInformationCategoryCreate",
  HEALTH_INFORMATION_CATEGORY_UPDATE = "healthInformationCategoryUpdate",
  HEALTH_INFORMATION_CATEGORY_DELETE = "healthInformationCategoryDelete",
  HEALTH_INFORMATION_CATEGORY_GET = "healthInformationCategoryGet",
  HEALTH_INFORMATION_CATEGORY_GET_ALL = "healthInformationCategoryGetAll",
  HEALTH_INFORMATION_RELATED_ARTICLES = "healthInformationRelatedArticles",

  COMMENT_CREATE = "commentCreate",
  COMMENT_UPDATE = "commentUpdate",
  COMMENT_DELETE = "commentDelete",
  COMMENT_GET = "commentGet",
  COMMENT_GET_ALL = "commentGetAll",

  MEDICINE_REQUEST_CREATE = "medicineRequestCreate",
  MEDICINE_REQUEST_UPDATE = "medicineRequestUpdate",
  MEDICINE_REQUEST_DELETE = "medicineRequestDelete",
  MEDICINE_REQUEST_GET = "medicineRequestGet",
  MEDICINE_REQUEST_GET_ALL = "medicineRequestGetAll",

  AGENT_REFER_GET = "agentReferenceGet",
  AGENT_REFER_GET_ALL = "agentReferenceGetAll",
  AGENT_REFER_DELETE = "agentReferenceDelete",
  AGENT_REFER_UPDATE = "agentReferenceUpdate",
  AGENT_REFER_CREATE = "agentReferenceCreate",

  AGENT_CASH_WITHDRAW_CREATE = "agentCashWithdrawCreate",
  AGENT_CASH_WITHDRAW_UPDATE = "agentCashWithdrawUpdate",
  AGENT_CASH_WITHDRAW_GET = "agentCashWithdrawGet",
  AGENT_CASH_WITHDRAW_GET_ALL = "agentCashWithdrawGetAll",
  AGENT_CASH_WITHDRAW_DELETE = "agentCashWithdrawDelete",

  ACTIVITY_LOG_CREATE = "activityLogCreate",
  ACTIVITY_LOG_UPDATE = "activityLogUpdate",
  ACTIVITY_LOG_DELETE = "activityLogDelete",
  ACTIVITY_LOG_GET = "activityLogGet",
  ACTIVITY_LOG_GET_ALL = "activityLogGetAll",

  NOTIFICATION_GET = "notificationGet",
  NOTIFICATION_GET_ALL = "notificationGetAll",
  NOTIFICATION_GET_ALL_USER = "notificationGetAllUser",
  NOTIFICATION_CREATE = "notificationCreate",
  NOTIFICATION_UPDATE = "notificationUpdate",
  NOTIFICATION_DELETE = "notificationDelete",
  NOTIFICATION_MARK_AS_READ = "notificationMarkAsRead",
  NOTIFICATION_MARK_AS_UNREAD = "notificationMarkAsUnread",

  OTP_SEND = "otpSend",
  OTP_VERIFIED = "otpVerified",
  OTP_VERIFIED_V2 = "otpVerifiedV2",
  OTP_CREATE = "otpCreate",
  OTP_UPDATE = "otpUpdate",
  OTP_DELETE = "otpDelete",
  OTP_GET = "otpGet",
  OTP_GET_ALL = "otpGetAll",

  BRAND_CREATE = "createBrand",
  BRAND_GET_ALL = "getBrands",
  BRAND_GET = "getBrandById",
  BRAND_UPDATE = "updateBrand",
  BRAND_DELETE = "deleteBrand",

  CATEGORY_CREATE = "createCategory",
  CATEGORY_GET_ALL = "getCategories",
  CATEGORY_GET_BY_ID = "getCategoryById",
  CATEGORY_UPDATE = "updateCategory",
  CATEGORY_DELETE = "deleteCategory",

  COMPANY_CREATE = "createCompany",
  COMPANY_GET_ALL = "getCompanyies",
  COMPANY_GET_BY_ID = "getCompanyById",
  COMPANY_UPDATE = "updateCompany",
  COMPANY_DELETE = "deleteCompany",

  GENERIC_CREATE = "createGeneric",
  GENERIC_GET_ALL = "getGenerics",
  GENERIC_GET_BY_ID = "getGenericById",
  GENERIC_UPDATE = "updateGeneric",
  GENERIC_DELETE = "deleteGeneric",

  PRODUCT_TYPE_CREATE = "createProductType",
  PRODUCT_TYPE_GET_ALL = "getProductTypes",
  PRODUCT_TYPE_GET_BY_ID = "getProductTypeById",
  PRODUCT_TYPE_UPDATE = "updateProductType",
  PRODUCT_TYPE_DELETE = "deleteProductType",

  STRENGTH_CREATE = "createStrength",
  STRENGTH_GET_ALL = "getStrengths",
  STRENGTH_GET_BY_ID = "getStrengthById",
  STRENGTH_UPDATE = "updateStrength",
  STRENGTH_DELETE = "deleteStrength",

  VARIANT_CREATE = "createVariant",
  VARIANT_GET_ALL = "getVariants",
  VARIANT_GET_BY_ID = "getVariantById",
  VARIANT_UPDATE = "updateVariant",
  VARIANT_DELETE = "deleteVariant",

  SEARCH_PRODUCT = "searchProduct",

  PRODUCT_CREATE = "createProduct",
  PRODUCT_GET_ALL = "getProducts",
  PRODUCT_GET_BY_ID = "getProductById",
  PRODUCT_GET_BY_SLUG = "getProductBySlug",
  PRODUCT_GET_BY_IDS = "getProductByIds",
  PRODUCT_UPDATE = "updateProduct",
  PRODUCT_DELETE = "deleteProduct",
  ALTERNATIVE_PRODUCT = "alternativeProduct",

  PRODUCT_VARIANT_CREATE = "createProductVariant",
  PRODUCT_VARIANT_GET_ALL = "getProductsVariant",
  PRODUCT_VARIANT_GET_BY_ID = "getProductVariantById",
  PRODUCT_VARIANT_UPDATE = "updateProductVariant",
  PRODUCT_VARIANT_UPDATE_MULTIPLE = "updateProductVariantMultiple",
  PRODUCT_VARIANT_DELETE = "deleteProductVariant",
  PRODUCT_VARIANT_GET_MANY_FOR_ORDER = "productGetManyForOrder",
  PRODUCT_VARIANT_GET_BY_IDS = "getProductByVariantIds",

  FEEDBACK_CREATE = "createFeedback",
  FEEDBACK_GET_ALL = "getFeedbackAll",
  FEEDBACK_GET = "getFeedback",
  FEEDBACK_UPDATE = "updateFeedback",
  FEEDBACK_DELETE = "deleteFeedback",

  FAVOURITE_CREATE = "createFavourite",
  FAVOURITE_GET_ALL = "favouriteGetAll",
  FAVOURITE_GET = "getFavourite",
  FAVOURITE_UPDATE = "updateFavourite",
  FAVOURITE_DELETE = "deleteFavourite",

  BANNER_CREATE = "bannerCreate",
  BANNER_GET_ALL = "bannerGetAll",
  BANNER_GET = "getBanner",
  BANNER_UPDATE = "updateBanner",
  BANNER_DELETE = "deleteBanner",

  TRENDING_CREATE = "trendingCreate",
  TRENDING_GET_ALL = "trendingGetAll",
  TRENDING_GET = "trendingGet",
  TRENDING_UPDATE = "trendingUpdate",
  TRENDING_DELETE = "trendingDelete",

  CAMPAIGN_CREATE = "campaignCreate",
  CAMPAIGN_GET_ALL = "campaignGetAll",
  CAMPAIGN_GET = "campaignGet",
  CAMPAIGN_UPDATE = "campaignUpdate",
  CAMPAIGN_DELETE = "campaignDelete",

  CAMPAIGN_PRODUCT_CREATE = "campaignProductCreate",
  CAMPAIGN_PRODUCT_GET_ALL = "campaignProductGetAll",
  CAMPAIGN_PRODUCT_GET = "campaignProductGet",
  CAMPAIGN_PRODUCT_UPDATE = "campaignProductUpdate",
  CAMPAIGN_PRODUCT_DELETE = "campaignProductDelete",

  /**************** Search ******************/
  PRODUCT_ALL_DATA = "productAllData",

  ORDER_CREATE = "orderCreate",
  ORDER_UPDATE = "orderUpdate",
  ORDER_DELETE = "orderDelete",
  ORDER_SOFT_DELETE = "orderSoftDelete",
  ORDER_GET = "orderGet",
  ORDER_GET_ALL = "orderGetAll",
  ADMIN_ORDER_GET_ALL = "adminOrderGetAll",
  ORDER_CHANGE_STATUS = `orderChangeStatus`,
  ORDER_PAID_STATUS = "orderPaidStatus",
  ORDER_STATISTICS = "orderStatistics",
  INVOICE_CREATE = "invoiceCreate",

  DELIVERY_FEE_CREATE = "deliveryFeeCreate",
  DELIVERY_FEE_UPDATE = "deliveryFeeUpdate",
  DELIVERY_FEE_DELETE = "deliveryFeeDelete",
  DELIVERY_FEE_GET = "deliveryFeeGet",
  DELIVERY_FEE_GET_ALL = "deliveryFeeGetAll",

  PAYMENT_SERVICE_CREATE = "paymentService",

  VOUCHER_CREATE = "voucherCreate",
  VOUCHER_GET_ALL = "voucherGetAll",
  VOUCHER_GET_BY_ID = "voucherGetById",
  VOUCHER_UPDATE = "voucherUpdate",
  VOUCHER_DELETE = "voucherDelete",
  VOUCHER_VALIDATE = "voucherValidate",

  USES_VOUCHER_CREATE = "usesVoucherCreate",
  USES_VOUCHER_GET_ALL = "usesVoucherGetAll",
  USES_VOUCHER_GET_BY_ID = "usesVoucherGetById",
  USES_VOUCHER_UPDATE = "usesVoucherUpdate",
  USES_VOUCHER_DELETE = "usesVoucherDelete",

  CHECKOUT = "checkout",
  /**************** MessagePattern Point ******************/
  ORDER_CREATE_EVENT = "orderCreateEvent",
  BEARER_TOKEN_VALIDATION = "tokenValidation",
  FILEUPLOADV2 = "fileuploadV2",

  SEND_NOTIFICATION = "send.notification",
  SUBSCRIBE = "subscribe",
}
